### ISSUE TITLE
CGI Program

### ISSUE THREAD

**Issue by zlsh80826** [afq984/UnixProgHW4TestCases#1]
In spec,
> You may detect a CGI script by using either the extension file name, e.g., .cgi, or the name of the containing directory, e.g., /cgi-bin/

**Comment by afq984** [comment]
I find it troublesome to handle the case when a *supposed* CGI program is not executable, e.g. permission 100 scripts or 400 binaries. However, it is unspecified in the spec, and the line you quoted says *may*, so I feel lazy and detect CGI programs by checking execute permission, and write that behavior in the submitted `README`.

You can modify test.py starting from L206 and install.sh to add more test files to change the behavior.

Ideally 5xx could be used in case of an error: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_errors
But those are not specified anyway.
